# Generated by Django 4.1.5 on 2023-02-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m', '0004_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='project',
            field=models.ManyToManyField(related_name='prj_tags', to='m.project'),
        ),
    ]
