# Generated by Django 4.1.5 on 2023-02-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m', '0005_alter_tag_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='vote',
            field=models.CharField(choices=[('up', 'up vote'), ('down', 'down vote')], default='up', max_length=4),
        ),
    ]
