# Generated by Django 4.1.5 on 2023-02-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m', '0006_review_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='project',
            field=models.ManyToManyField(null=True, related_name='prj_tags', to='m.project'),
        ),
    ]
