# Generated by Django 4.1.5 on 2023-02-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m', '0007_alter_tag_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project',
            field=models.ManyToManyField(null=True, related_name='projects', to='m.project'),
        ),
    ]
