# Generated by Django 4.1.5 on 2023-02-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m', '0010_remove_project_project_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='review_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='review_total',
            field=models.IntegerField(default=0),
        ),
    ]
